function pickupLineGenerator(){
    const lines = ["Well, here I am. What are your other two wishes?", 
    "Hey, my name's Microsft. Can I crash at your place tonight?", 
    "Are you French? Because Eiffel for you.", 
    "Do you like raisins? How do you feel about a date?", 
    "There is something wrong with my cell phone. It doesn't have your number in it.",
    "If I could rearrange the alphabet, I’d put ‘U’ and ‘I’ together.",
    "Aside from being sexy, what do you do for a living?",
    "I must be a snowflake, because I've fallen for you.",
    "Are you from Tennessee? Because you're the only 10 I see!",
    "If you were a Transformer… you’d be Optimus Fine.",
    "Are you a parking ticket? Because you’ve got FINE written all over you.",
    "I wish I were cross-eyed so I can see you twice.",
    "I must be in a museum, because you truly are a work of art.",
    "Do you believe in love at first sight—or should I walk by again?",
    "I'm no photographer, but I can picture us together.",
    "Feel my shirt. Know what it’s made of? Boyfriend material.",
    "Are you related to Jean-Claude Van Damme? Because Jean-Claude Van Damme you’re sexy!",
    "If you were a chicken, you’d be impeccable.",
    "Did your license get suspended for driving all these guys crazy?",
    "I’m learning about important dates in history. Wanna be one of them?",
    "Baby, if you were words on a page, you’d be fine print.",
    "Did you just come out of the oven? Because you’re hot.",
    "It’s a good thing I have my library card because I am totally checking you out.",
    "I was blinded by your beauty; I’m going to need your name and phone number for insurance purposes.",
    "I was wondering if you had an extra heart. Because mine was just stolen.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Are you a bank loan? Because you got my interest.",
    "Are you a time traveler? Cause I see you in my future!",
    "Can I follow you where you’re going right now? Because my parents always told me to follow my dreams.",
    "Is this the Hogwarts Express? Because it feels like you and I are headed somewhere magical.",
    "Life without you is like a broken pencil…pointless.",
    "Something’s wrong with my eyes because I can’t take them off you.",
    "My love for you is like diarrhea, I just can't hold it in.",
    "Somebody better call God, because he’s missing an angel.",
    "We’re not socks, but I think we’d make a great pair.",
    "You must be tired because you've been running through my mind all night.",
    "Do you have a map? I keep getting lost in your eyes.",
    "Do you have a BandAid? I just scraped my knee falling for you.",
    "Do you like Star Wars? Because Yoda only one for me!",
    "Did you invent the airplane? Because you seem Wright for me.",
    "Did the sun come out or did you just smile at me?",
    "Do you know CPR? Because you are taking my breath away!",
    "Are you a magician? Because whenever I look at you, everyone else disappears!",
    "Do I know you? ‘Cause you look a lot like my next girlfriend/boyfriend.",
    "They say Disneyland is the happiest place on earth. Well apparently, no one has ever been standing next to you.",
    "For some reason, I was feeling a little off today. But when you came along, you definitely turned me on.",
    "I seem to have lost my phone number. Can I have yours?",
    "Is there an airport nearby or is it my heart taking off?",
    "Was your dad a boxer? Because damn, you’re a knockout!",
    "Would you grab my arm, so I can tell my friends I’ve been touched by an angel?",
    "There’s only one thing I want to change about you, and that’s your last name.",
    "Hi, how was heaven when you left it?",
    "Is your dad a terrorist? Cause you’re the bomb.",
    "Kiss me if I’m wrong, but dinosaurs still exist, right?",
    "Hey, you’re pretty and I’m cute. Together we’d be Pretty Cute.",
    "Can I follow you home? Cause my parents always told me to follow my dreams.",
    "If nothing lasts forever, will you be my nothing?",
    "Was you father an alien? Because there’s nothing else like you on Earth!",
    "Was your father a thief? ‘Cause someone stole the stars from the sky and put them in your eyes.",
    "I’d say God Bless you, but it looks like he already did.",
    "Can you take me to the doctor? Because I just broke my leg falling for you.",
    "You don’t need keys to drive me crazy.",
    "I’m no mathematician, but I’m pretty good with numbers. Tell you what, give me yours and watch what I can do with it.",
    "You must be a broom, ‘cause you just swept me off my feet.",
    "Hello. Cupid called. He wants to tell you that he needs my heart back.",
    "If I could rearrange the alphabet, I'd put 'I' and 'U' together.",
    "I wasn't always religious. But I am now, because you're the answer to all my prayers.",
    "You are the reason even Santa has a naughty list.",
    "Is your name Ariel? Cause we Mermaid for each other.",
    "I want our love to be like the number Pi: irrational and never-ending.",
    "I think you're suffering from a lack of vitamin me.",
    "You must be a high test score. Because I want to take you home and show you to my mother.",
    "Want a raisin? No? Well, how about a date?",
    "Are your parents bakers? Because you're a cutie pie!",
    "If you were a vegetable, you would be a cute-cumber!",
    "I'm glad I remembered to bring my library card. 'Cause I am totally checking you out!",
    "You must be made of cheese. Because you're looking Gouda tonight!",
    "You must be a campfire. Because you're super hot and I want s'more.",
    "I'm in the mood for pizza. A pizza you, that is!",
    "Are you a loan? 'Cause you've got my interest!",
    "Are you Siri? Because you autocomplete me!"]

    var line = lines[Math.floor(Math.random() * lines.length)];
    console.log(line)
    document.getElementById("pickupLine").innerHTML = line;
}